// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilCreateUserRequest is returned when the CreateUserRequest is nil.
	ErrNilCreateUserRequest = errors.New("input CreateUserRequest is nil")

	// ErrCreateUserRequestFirstNameRequiredValidation is returned when the FirstName is required but not provided.
	ErrCreateUserRequestFirstNameRequiredValidation = govaliderrors.ValidationError{Reason: "field FirstName is required", Path: "CreateUserRequest.FirstName", Type: "required"}

	// ErrCreateUserRequestLastNameRequiredValidation is returned when the LastName is required but not provided.
	ErrCreateUserRequestLastNameRequiredValidation = govaliderrors.ValidationError{Reason: "field LastName is required", Path: "CreateUserRequest.LastName", Type: "required"}

	// ErrCreateUserRequestAgeRequiredValidation is returned when the Age is required but not provided.
	ErrCreateUserRequestAgeRequiredValidation = govaliderrors.ValidationError{Reason: "field Age is required", Path: "CreateUserRequest.Age", Type: "required"}

	// ErrCreateUserRequestCityRequiredValidation is returned when the City is required but not provided.
	ErrCreateUserRequestCityRequiredValidation = govaliderrors.ValidationError{Reason: "field City is required", Path: "CreateUserRequest.City", Type: "required"}

	// ErrCreateUserRequestEmailRequiredValidation is returned when the Email is required but not provided.
	ErrCreateUserRequestEmailRequiredValidation = govaliderrors.ValidationError{Reason: "field Email is required", Path: "CreateUserRequest.Email", Type: "required"}
)

func ValidateCreateUserRequest(t *CreateUserRequest) error {
	if t == nil {
		return ErrNilCreateUserRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.FirstName == "" {
		err := ErrCreateUserRequestFirstNameRequiredValidation
		err.Value = t.FirstName
		errs = append(errs, err)
	}

	if t.LastName == "" {
		err := ErrCreateUserRequestLastNameRequiredValidation
		err.Value = t.LastName
		errs = append(errs, err)
	}

	if t.Age == 0 {
		err := ErrCreateUserRequestAgeRequiredValidation
		err.Value = t.Age
		errs = append(errs, err)
	}

	if t.City == "" {
		err := ErrCreateUserRequestCityRequiredValidation
		err.Value = t.City
		errs = append(errs, err)
	}

	if t.Email == "" {
		err := ErrCreateUserRequestEmailRequiredValidation
		err.Value = t.Email
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*CreateUserRequest)(nil)

func (t *CreateUserRequest) Validate() error {
	return ValidateCreateUserRequest(t)
}
