// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilUserIDUri is returned when the UserIDUri is nil.
	ErrNilUserIDUri = errors.New("input UserIDUri is nil")

	// ErrUserIDUriIDRequiredValidation is returned when the ID is required but not provided.
	ErrUserIDUriIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ID is required", Path: "UserIDUri.ID", Type: "required"}
)

func ValidateUserIDUri(t *UserIDUri) error {
	if t == nil {
		return ErrNilUserIDUri
	}

	var errs govaliderrors.ValidationErrors

	if t.ID == 0 {
		err := ErrUserIDUriIDRequiredValidation
		err.Value = t.ID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*UserIDUri)(nil)

func (t *UserIDUri) Validate() error {
	return ValidateUserIDUri(t)
}
