// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilUpdateUserRequest is returned when the UpdateUserRequest is nil.
	ErrNilUpdateUserRequest = errors.New("input UpdateUserRequest is nil")

	// ErrUpdateUserRequestIDRequiredValidation is returned when the ID is required but not provided.
	ErrUpdateUserRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ID is required", Path: "UpdateUserRequest.ID", Type: "required"}
)

func ValidateUpdateUserRequest(t *UpdateUserRequest) error {
	if t == nil {
		return ErrNilUpdateUserRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ID == 0 {
		err := ErrUpdateUserRequestIDRequiredValidation
		err.Value = t.ID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*UpdateUserRequest)(nil)

func (t *UpdateUserRequest) Validate() error {
	return ValidateUpdateUserRequest(t)
}
