/**
 * The migration plan document is a contract between two processes.
 *
 * The agent writes `.dakcoder/migration/plan.md` (`PROGRESS_PATH` in
 * `apps/agent/src/dakcoder_agent/migration.py`) and the Migration view parses
 * it here. Nothing had ever written it: the view was permanently empty, its
 * welcome text pointed at a file that did not exist, and a developer whose
 * migration was under way had nowhere to see the plan or track progress.
 *
 * So the format is now load-bearing in both directions, and these tests pin the
 * half this process owns. The sample below is real output — copied from the
 * generator, not written to suit the parser — because a fixture written to suit
 * the parser proves only that the fixture is well-formed.
 */

import { strict as assert } from 'node:assert';
import { describe, it } from 'node:test';
import * as path from 'node:path';
import Module from 'node:module';

// ── a minimal `vscode` stand-in ─────────────────────────────────────────────
//
// `parseMigrationPlan` is a pure function over text, but it lives in a module
// that imports `vscode` for the view around it. Booting an Electron host to
// parse a string is not worth it; resolving `vscode` to a shim is what
// `state.test.ts` does for the same reason. If the parser ever reaches for a
// real editor API this throws by absence rather than passing on a stub.
const vscodeShim = {
  EventEmitter: class {
    readonly event = () => ({ dispose: () => {} });
    fire(): void {}
    dispose(): void {}
  },
  Disposable: { from: () => ({ dispose: () => {} }) },
  l10n: { t: (template: string) => template },
  window: {},
  workspace: {},
  Uri: { joinPath: () => undefined },
  ThemeIcon: class {},
  ThemeColor: class {},
  TreeItem: class {},
  TreeItemCollapsibleState: { None: 0, Collapsed: 1, Expanded: 2 },
  MarkdownString: class {
    value = '';
    appendMarkdown(): void {}
  },
  EventEmitter_: undefined,
};

const originalResolve = (Module as unknown as { _resolveFilename: Function })._resolveFilename;
(Module as unknown as { _resolveFilename: Function })._resolveFilename = function (
  request: string,
  ...rest: unknown[]
) {
  if (request === 'vscode') return path.join(__dirname, '__vscode__.js');
  return originalResolve.call(this, request, ...rest);
};
require.cache[path.join(__dirname, '__vscode__.js')] = {
  id: '__vscode__',
  filename: path.join(__dirname, '__vscode__.js'),
  loaded: true,
  exports: vscodeShim,
} as unknown as NodeModule;

// eslint-disable-next-line @typescript-eslint/no-var-requires
const { parseMigrationPlan } = require('../wizard') as typeof import('../wizard');

/** Real output of `progress_document`, mid-migration. */
const PLAN = [
  '# Migration plan',
  '',
  'Generated by dakcoder. Edits are overwritten on the next turn — to change',
  'the work, say so in the chat and the plan is rewritten from there.',
  '',
  '- **Branch:** `template-conversion`, cut from `development`',
  '- **Phases:** 1 of 3 closed',
  '- **Routes recorded before the migration:** 93 — a route lost in conversion is caught when the last phase closes',
  '- **Updated:** 2026-09-11 17:28 UTC',
  '',
  '## Phases',
  '',
  '1. **branch** — cut template-conversion · **done**',
  '   - Parts: check, confirm, cut',
  '2. **deps** — swap api-* for n-api-* · **open**',
  '   - Parts: go.mod, main.go, bootstrap',
  '   - Steps: 0 of 2 settled',
  '3. **handlers** — convert every handler · pending',
  '   - Parts: imports, Base, Routes, DTOs',
  '',
  '## Units',
  '',
  '| Unit | Kind | Classification | Status | Rules | Commit |',
  '|---|---|---|---|---|---|',
  '| go.mod | go.mod | MIGRATE | pending | swap the dependencies | |',
  '| handler/objection.go | imports | MIGRATE | done | convert it | |',
  '| routes/routes.go | routes | SKIP | skipped | retired by the template | |',
  '',
  '## Still to do',
  '',
  '- **deps** — swap api-* for n-api-*',
  '- **handlers** — convert every handler',
  '',
  'Each phase is planned when it opens, against the workspace the phase',
  'before it left. Say when to start the next one.',
  '',
  '## Log',
  '',
  '- 2026-09-11 17:28 UTC — phase 1 of 3, branch, closed',
  '',
].join('\n');

describe('the migration plan the agent writes', () => {
  it('is read by the view as one unit per step', () => {
    const { units } = parseMigrationPlan(PLAN);
    assert.deepEqual(
      units.map((u) => u.path),
      ['go.mod', 'handler/objection.go', 'routes/routes.go'],
    );
  });

  it('carries the status the agent derived, not a default', () => {
    const { units } = parseMigrationPlan(PLAN);
    assert.deepEqual(
      units.map((u) => u.status),
      ['pending', 'done', 'skipped'],
    );
  });

  it('excludes a skipped step from the work, and keeps the rest in it', () => {
    const { units } = parseMigrationPlan(PLAN);
    assert.deepEqual(
      units.map((u) => u.classification),
      ['MIGRATE', 'MIGRATE', 'SKIP'],
    );
  });

  it('finds the table, so the view is not empty', () => {
    const { columns } = parseMigrationPlan(PLAN);
    assert.ok(columns, 'no table with a path column was found');
    assert.equal(columns?.path, 0);
    assert.equal(columns?.status, 3);
  });

  // The trap, and the reason the phases are a numbered list.
  //
  // `unitFromTask` reads *every* `- [ ]` line in the document as a unit, so a
  // phase rendered as a checklist — which is the obvious way to render one —
  // would appear in the tree as a file that does not exist, above the files
  // that do.
  it('does not mistake a phase or a heading for a unit', () => {
    const { units } = parseMigrationPlan(PLAN);
    for (const unit of units) {
      assert.ok(
        unit.path.includes('.') || unit.path.includes('/'),
        `${unit.path} is not a path; something in the prose parsed as a unit`,
      );
    }
  });

  it('survives a document written before any phase was planned', () => {
    const early = ['# Migration plan', '', '- **Branch:** not cut yet.', ''].join('\n');
    const { units, columns } = parseMigrationPlan(early);
    assert.equal(units.length, 0);
    assert.equal(columns, undefined);
  });
});
