package workspace

import (
	"os"
	"path/filepath"
	"testing"
)

func write(t *testing.T, root, rel, body string) {
	t.Helper()
	p := filepath.Join(root, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestClassify(t *testing.T) {
	cases := map[string]Layer{
		"main.go":                    LayerMain,
		"core/domain/user.go":        LayerDomain,
		"core/port/response.go":      LayerPort,
		"repo/postgres/user.go":      LayerRepo,
		"repo/ecms/file.go":          LayerRepo,
		"handler/user.go":            LayerHandler,
		"handler/request.go":         LayerHandler,
		"handler/request/request.go": LayerHandler,
		"handler/response/user.go":   LayerResponse,
		"bootstrap/bootstrapper.go":  LayerBootstrap,
		"routes/routes.go":           LayerRoutes,
		"internal/thing/thing.go":    LayerOther,
	}
	for rel, want := range cases {
		t.Run(rel, func(t *testing.T) {
			if got := classify(rel, false); got != want {
				t.Errorf("classify(%q) = %v, want %v", rel, got, want)
			}
		})
	}
	if got := classify("handler/user_test.go", true); got != LayerTest {
		t.Errorf("test file classified as %v, want %v", got, LayerTest)
	}
}

// TestPruneDirsAreNotDescended is the performance guard.
//
// The rule is not "these files are excluded" but "this tree is never walked".
// A post-hoc filter still stats every entry, which on Windows means the
// antivirus filter driver intercepts each one — measured at 1.6s to keep 200
// files out of 16,680 on a comparable tree. If this regresses, the linter stops
// being usable in an edit loop.
func TestPruneDirsAreNotDescended(t *testing.T) {
	root := t.TempDir()
	write(t, root, "go.mod", "module pisapi\n\ngo 1.25.0\n")
	write(t, root, "handler/user.go", "package handler\n")
	write(t, root, "vendor/github.com/x/y/z.go", "package z\n")
	write(t, root, "node_modules/pkg/index.go", "package pkg\n")
	write(t, root, ".git/hooks/thing.go", "package hooks\n")
	write(t, root, "bin/tool.go", "package main\n")

	ws, err := Load(root)
	if err != nil {
		t.Fatalf("load: %v", err)
	}
	if len(ws.Files) != 1 {
		t.Errorf("loaded %d files, want 1", len(ws.Files))
		for _, f := range ws.Files {
			t.Logf("  %s", f.Rel)
		}
	}
	if _, ok := ws.File("handler/user.go"); !ok {
		t.Error("handler/user.go was not loaded")
	}
}

func TestGeneratedDetection(t *testing.T) {
	root := t.TempDir()
	write(t, root, "go.mod", "module pisapi\n\ngo 1.25.0\n")
	write(t, root, "handler/request_x_validator.go",
		"// Code generated by govalid; DO NOT EDIT.\npackage handler\n")
	write(t, root, "handler/user.go", "package handler\n")

	ws, err := Load(root)
	if err != nil {
		t.Fatalf("load: %v", err)
	}
	if len(ws.Files) != 1 {
		t.Errorf("generated file should be excluded by default; loaded %d", len(ws.Files))
	}

	ws2, err := Load(root, WithGenerated())
	if err != nil {
		t.Fatalf("load with generated: %v", err)
	}
	if len(ws2.Files) != 2 {
		t.Fatalf("WithGenerated loaded %d files, want 2", len(ws2.Files))
	}
	f, ok := ws2.File("handler/request_x_validator.go")
	if !ok {
		t.Fatal("validator not loaded")
	}
	if !f.Generated {
		t.Error("validator not marked Generated")
	}
}

// TestGeneratedDetectionUsesMarkerNotFilename: a file named *_validator.go
// without the marker is hand-written, and that is precisely what the
// validator-generated rule needs to catch.
func TestGeneratedDetectionUsesMarkerNotFilename(t *testing.T) {
	root := t.TempDir()
	write(t, root, "go.mod", "module pisapi\n\ngo 1.25.0\n")
	write(t, root, "handler/request_x_validator.go", "package handler\n\n// hand written\n")

	ws, err := Load(root, WithGenerated())
	if err != nil {
		t.Fatalf("load: %v", err)
	}
	f, ok := ws.File("handler/request_x_validator.go")
	if !ok {
		t.Fatal("file not loaded")
	}
	if f.Generated {
		t.Error("file without the marker must not be treated as generated")
	}
}

// TestBrokenFileStillParses is the property that makes this linter usable in
// the Debugger loop: the agent runs it precisely when the build is broken.
func TestBrokenFileStillParses(t *testing.T) {
	root := t.TempDir()
	write(t, root, "go.mod", "module pisapi\n\ngo 1.25.0\n")
	// A type error, not a syntax error: undefined symbol, wrong arity.
	write(t, root, "handler/user.go", `package handler

import serverRoute "gitlab.cept.gov.in/it-2.0-common/n-api-server/route"

type UserHandler struct{}

func (h *UserHandler) Get(sctx *serverRoute.Context, _ struct{}) (*Missing, error) {
	return nil, undefinedFunction()
}
`)
	ws, err := Load(root)
	if err != nil {
		t.Fatalf("load: %v", err)
	}
	f, ok := ws.File("handler/user.go")
	if !ok {
		t.Fatal("file with unresolved symbols was not loaded")
	}
	if f.AST == nil {
		t.Fatal("AST is nil")
	}
	// The signature is still fully inspectable, which is what rules need.
	if f.Layer != LayerHandler {
		t.Errorf("layer = %v, want handler", f.Layer)
	}
}

func TestLoadGoMod(t *testing.T) {
	root := t.TempDir()
	write(t, root, "go.mod", `module pisapi

go 1.25.0

require (
	github.com/Masterminds/squirrel v1.5.4
	github.com/jackc/pgx/v5 v5.7.6
	go.uber.org/fx v1.24.0
)

require (
	github.com/beorn7/perks v1.0.1 // indirect
)
`)
	ws, err := Load(root)
	if err != nil {
		t.Fatalf("load: %v", err)
	}
	if ws.ModulePath != "pisapi" {
		t.Errorf("module = %q, want pisapi", ws.ModulePath)
	}
	if ws.GoVersion != "1.25.0" {
		t.Errorf("go version = %q, want 1.25.0", ws.GoVersion)
	}
	if len(ws.Requires) != 3 {
		t.Errorf("direct requires = %d, want 3 (indirect must be excluded)", len(ws.Requires))
		for _, r := range ws.Requires {
			t.Logf("  %s %s", r.Path, r.Version)
		}
	}
}

// TestMissingGoModIsNotFatal: the agent can legitimately create a state with no
// go.mod (mid-scaffold), and the linter must still report what it can.
func TestMissingGoModIsNotFatal(t *testing.T) {
	root := t.TempDir()
	write(t, root, "handler/user.go", "package handler\n")
	ws, err := Load(root)
	if err != nil {
		t.Fatalf("load without go.mod: %v", err)
	}
	if ws.ModulePath != "" {
		t.Errorf("module path = %q, want empty", ws.ModulePath)
	}
	if len(ws.Files) != 1 {
		t.Errorf("loaded %d files, want 1", len(ws.Files))
	}
}

func TestImportsAny(t *testing.T) {
	root := t.TempDir()
	write(t, root, "go.mod", "module pisapi\n\ngo 1.25.0\n")
	write(t, root, "handler/user.go", "package handler\n\nimport (\n\tsq \"github.com/Masterminds/squirrel\"\n)\n\nvar _ = sq.Eq{}\n")
	ws, err := Load(root)
	if err != nil {
		t.Fatalf("load: %v", err)
	}
	f, _ := ws.File("handler/user.go")
	path, spec, ok := f.ImportsAny("github.com/Masterminds/squirrel")
	if !ok {
		t.Fatal("import not found")
	}
	if path != "github.com/Masterminds/squirrel" {
		t.Errorf("path = %q", path)
	}
	if spec == nil {
		t.Error("spec is nil; a rule could not report a position")
	}
	if _, _, ok := f.ImportsAny("github.com/nope"); ok {
		t.Error("unexpected match")
	}
}
