"""The loopback: the small HTTP+SSE endpoint the extension talks to.

**This is not the gateway.** No auth beyond a loopback token, no quota, no model
key. It runs on the developer's machine, binds to 127.0.0.1, and its only job is
to let the extension drive a run and watch it happen. Model traffic still leaves
through the gateway's ``/v1/llm`` proxy, which is what keeps quota and audit
unbypassable (Part A §15.4).

    POST /v1/tasks                      start a run; returns the session
    GET  /v1/sessions/{id}/events       live SSE, resumable with since_id
    GET  /v1/sessions                   the tree the extension renders
    GET  /v1/sessions/{id}              detail, optionally with the transcript
    POST /v1/sessions/{id}/abort        stop it
    POST /v1/sessions/{id}/revert       restore what it touched to HEAD
    POST /v1/approvals/{id}             accept / reject / edit
    GET  /v1/health                     version, toolchain, readiness
    GET  /v1/tools                      contract C1

**The loop is synchronous and this is not.** Two bridges are needed and both are
places where a naive version breaks quietly:

* The run executes in a worker thread and pushes events across with
  ``call_soon_threadsafe``. Running it inline would block the event loop for the
  whole task — including the abort endpoint, which is precisely the one that has
  to answer while a run is in flight.
* An approval blocks the loop thread on a ``threading.Event`` that the HTTP
  handler sets. That is why the loop must not run on the event loop: waiting for
  a decision that arrives over HTTP would otherwise deadlock the server that has
  to deliver it.

**Version pinning is a first-class response field.** Part B §15: silent version
skew across a client/server boundary is the failure that costs the most support
time, so ``/v1/health`` reports the API version and the extension refuses to
proceed on a mismatch rather than failing later in a way nobody can attribute.
"""

from __future__ import annotations

import asyncio
import secrets
import threading
import uuid
from collections.abc import AsyncIterator
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

from fastapi import FastAPI, Header, HTTPException, Query, Request
from fastapi.responses import JSONResponse, StreamingResponse

from dakcoder_shared.envelope import Event, EventType

from .loop import AgentLoop
from .modes import Mode
from .session import Session, SessionStore, Status
from .tools.router import ApprovalRequest

__all__ = ["API_VERSION", "Loopback", "PendingApproval", "create_app"]

#: The contract version the extension pins against. Bumped when a response shape
#: changes in a way a client could not have anticipated — never for an additive
#: field, because C2's rule is that unknown types and fields are ignored.
API_VERSION = "1.0"

#: How long a run waits for an approval before giving up. Long enough for someone
#: to read a seven-file scaffold; short enough that a developer who closed the
#: window does not leave a thread parked until the process ends.
APPROVAL_TIMEOUT = 600.0


@dataclass
class PendingApproval:
    """One decision the run is blocked on."""

    id: str
    session_id: str
    request: ApprovalRequest
    #: Set by the HTTP handler; the loop thread is waiting on it.
    decided: threading.Event = field(default_factory=threading.Event)
    approved: bool = False
    #: An `edit` decision: corrected arguments. §9 calls this the standout —
    #: fixing the agent's arguments beats rejecting and re-prompting, and it
    #: keeps the developer in the loop without costing a turn.
    arguments: dict[str, Any] | None = None
    at: datetime = field(default_factory=lambda: datetime.now(tz=timezone.utc))

    def as_dict(self) -> dict[str, Any]:
        return {"id": self.id, "session_id": self.session_id, **self.request.as_dict()}


class Loopback:
    """The runtime the extension drives. One workspace, many sessions."""

    def __init__(
        self,
        workspace: Path,
        build_loop: Callable[[Session, Callable[[ApprovalRequest], bool]], AgentLoop],
        *,
        token: str = "",
        tool_catalog: dict[str, Any] | None = None,
        version: str = "dev",
        gateway_url: str = "",
    ) -> None:
        self.workspace = workspace
        self.build_loop = build_loop
        # A random token, generated by the extension and passed in the spawn
        # environment. It authenticates the *extension to its own runtime* — a
        # different question from who the developer is (§15.3), and the only one
        # a process on loopback can answer.
        self.token = token or secrets.token_urlsafe(32)
        self.sessions = SessionStore(workspace)
        self.tool_catalog = tool_catalog or {}
        self.version = version
        self.gateway_url = gateway_url
        self.approvals: dict[str, PendingApproval] = {}
        self.ready: dict[str, Any] = {"prewarmed": False}

    # -- running a task -----------------------------------------------------

    def start(self, task: str, *, mode: Mode = Mode.PLANNER, acceptance=()) -> Session:
        session = self.sessions.create(task)
        loop = asyncio.get_running_loop()

        def approve(request: ApprovalRequest) -> bool:
            return self._await_decision(session, request)

        agent = self.build_loop(session, approve)
        agent.cancelled = session.cancel.is_set

        def emit(event: Event) -> None:
            """Hand an event to the event loop, or record it directly if the
            loop has gone.

            A server shutting down while a run is in flight closes the loop, and
            an unguarded `call_soon_threadsafe` then raises *inside the worker
            thread* — killing it with an unhandled exception and leaving the
            session stuck at "running" forever. Recording directly keeps the
            transcript complete for whoever reads it next; there is simply
            nobody live to deliver it to.
            """
            try:
                loop.call_soon_threadsafe(session.record, event)
            except RuntimeError:
                session.record(event)

        def run() -> None:
            try:
                for event in agent.run(task, acceptance=acceptance, start=mode):
                    emit(event)
            except Exception as exc:  # noqa: BLE001 - a crashed run must still close
                emit(Event(EventType.ERROR, {"message": f"the run failed: {exc}"}))
                emit(Event(EventType.END, {"outcome": "error"}))
                session.status = Status.ERROR
                session.summary = str(exc)
                session.finished_at = datetime.now(tz=timezone.utc)
            else:
                if agent.result is not None:
                    session.finish(agent.result)
            finally:
                # Every approval this run was waiting on is released, whichever
                # way the run ended. A crashed run holding a pending approval
                # leaves the extension showing a card nothing will ever answer.
                self._release(session.id)

        threading.Thread(target=run, name=f"dakcoder-{session.id}", daemon=True).start()
        return session

    def _await_decision(self, session: Session, request: ApprovalRequest) -> bool:
        """Block the loop thread until the developer decides, or time runs out."""
        pending = PendingApproval(uuid.uuid4().hex[:12], session.id, request)
        self.approvals[pending.id] = pending

        if not pending.decided.wait(timeout=APPROVAL_TIMEOUT):
            # A timeout is a refusal, not an approval. Nobody looked, so nobody
            # agreed — and the failure mode of the opposite choice is a write
            # that happened while the developer was at lunch.
            self.approvals.pop(pending.id, None)
            return False

        self.approvals.pop(pending.id, None)
        if pending.approved and pending.arguments is not None:
            request.arguments.clear()
            request.arguments.update(pending.arguments)
        return pending.approved

    def _release(self, session_id: str) -> None:
        for pending in [p for p in self.approvals.values() if p.session_id == session_id]:
            pending.approved = False
            pending.decided.set()

    def pending_for(self, session_id: str) -> list[PendingApproval]:
        return [p for p in self.approvals.values() if p.session_id == session_id]


def create_app(runtime: Loopback) -> FastAPI:
    app = FastAPI(title="dakcoderd", version=runtime.version)
    app.state.runtime = runtime

    def authorise(authorization: str | None) -> None:
        """The loopback token.

        Bound to 127.0.0.1, so this is not defending against the network — it is
        defending against *other processes on the same machine*, which on a
        developer laptop includes every npm postinstall script and browser
        extension that can reach localhost. `secrets.compare_digest` because a
        timing side channel on a local socket is entirely practical.
        """
        expected = f"Bearer {runtime.token}"
        if not authorization or not secrets.compare_digest(authorization, expected):
            raise HTTPException(status_code=401, detail="invalid loopback token")

    def session_or_404(session_id: str) -> Session:
        session = runtime.sessions.get(session_id)
        if session is None:
            raise HTTPException(status_code=404, detail=f"no session {session_id}")
        return session

    # -- readiness ----------------------------------------------------------

    @app.get("/v1/health")
    async def health() -> dict[str, Any]:
        """No token required.

        A health check that needs a credential cannot tell the extension whether
        the credential path is the thing that is broken — and this is the
        endpoint it polls for up to sixty seconds while deciding whether the
        runtime came up at all.
        """
        return {
            "ok": True,
            "api_version": API_VERSION,
            "version": runtime.version,
            "workspace": str(runtime.workspace),
            "gateway": runtime.gateway_url,
            "ready": runtime.ready,
            "sessions": {
                "total": len(runtime.sessions.list()),
                "running": sum(1 for s in runtime.sessions.list() if s.running),
            },
        }

    @app.get("/v1/tools")
    async def tools(authorization: str | None = Header(default=None)) -> dict[str, Any]:
        authorise(authorization)
        return runtime.tool_catalog

    # -- tasks --------------------------------------------------------------

    @app.post("/v1/tasks")
    async def start_task(
        body: dict[str, Any], authorization: str | None = Header(default=None)
    ) -> dict[str, Any]:
        authorise(authorization)
        task = str(body.get("task", "")).strip()
        if not task:
            raise HTTPException(status_code=400, detail="task is required")

        session = runtime.start(
            task,
            mode=Mode(str(body.get("mode", "planner"))),
            acceptance=tuple(body.get("acceptance") or ()),
        )
        return session.as_dict()

    # -- the event stream ---------------------------------------------------

    @app.get("/v1/sessions/{session_id}/events")
    async def events(
        session_id: str,
        request: Request,
        since_id: int = Query(default=0),
        last_event_id: str | None = Header(default=None, alias="Last-Event-ID"),
        authorization: str | None = Header(default=None),
    ) -> StreamingResponse:
        """Live events, resumable.

        Part B §14's gap: a dropped connection today loses the live view of a run
        that is still executing server-side, and the developer cannot tell that
        from the run having died. Replaying from ``since_id`` closes it.

        ``Last-Event-ID`` is honoured because that is what a browser's
        ``EventSource`` sends automatically on reconnect — a client that does
        nothing special still resumes correctly.
        """
        authorise(authorization)
        session = session_or_404(session_id)

        resume_from = since_id
        if last_event_id and last_event_id.isdigit():
            resume_from = max(resume_from, int(last_event_id))

        return StreamingResponse(
            _stream(session, resume_from, request),
            media_type="text/event-stream",
            headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
        )

    # -- the sessions tree --------------------------------------------------

    @app.get("/v1/sessions")
    async def list_sessions(
        status: str | None = None, authorization: str | None = Header(default=None)
    ) -> dict[str, Any]:
        authorise(authorization)
        return {"sessions": [s.as_dict() for s in runtime.sessions.list(status=status)]}

    @app.get("/v1/sessions/{session_id}")
    async def get_session(
        session_id: str,
        transcript: bool = False,
        authorization: str | None = Header(default=None),
    ) -> dict[str, Any]:
        authorise(authorization)
        session = session_or_404(session_id)
        payload = session.as_dict(transcript=transcript)
        payload["pending_approvals"] = [
            p.as_dict() for p in runtime.pending_for(session_id)
        ]
        return payload

    @app.delete("/v1/sessions/{session_id}")
    async def delete_session(
        session_id: str, authorization: str | None = Header(default=None)
    ) -> dict[str, Any]:
        authorise(authorization)
        session = session_or_404(session_id)
        if session.running:
            raise HTTPException(status_code=409, detail="abort the session before deleting it")
        runtime.sessions.delete(session_id)
        return {"deleted": session_id}

    @app.post("/v1/sessions/{session_id}/abort")
    async def abort(
        session_id: str, authorization: str | None = Header(default=None)
    ) -> dict[str, Any]:
        authorise(authorization)
        session = session_or_404(session_id)
        session.abort()
        runtime._release(session_id)
        return {"aborting": session_id, "status": str(session.status)}

    # -- revert -------------------------------------------------------------

    @app.get("/v1/sessions/{session_id}/revert")
    async def revert_plan(
        session_id: str, authorization: str | None = Header(default=None)
    ) -> dict[str, Any]:
        """What a revert would do. §12 asks for the confirmation to list the
        exact paths, because "revert my last task" is easy to fire by accident."""
        authorise(authorization)
        return runtime.sessions.plan_revert(session_or_404(session_id)).as_dict()

    @app.post("/v1/sessions/{session_id}/revert")
    async def revert(
        session_id: str, authorization: str | None = Header(default=None)
    ) -> dict[str, Any]:
        authorise(authorization)
        session = session_or_404(session_id)
        if session.running:
            raise HTTPException(
                status_code=409, detail="a running session cannot be reverted; abort it first"
            )
        return runtime.sessions.revert(session).as_dict()

    # -- approvals ----------------------------------------------------------

    @app.get("/v1/approvals")
    async def list_approvals(
        authorization: str | None = Header(default=None),
    ) -> dict[str, Any]:
        authorise(authorization)
        return {"approvals": [p.as_dict() for p in runtime.approvals.values()]}

    @app.post("/v1/approvals/{approval_id}")
    async def decide(
        approval_id: str,
        body: dict[str, Any],
        authorization: str | None = Header(default=None),
    ) -> dict[str, Any]:
        """Accept, reject, or edit.

        ``edit`` replaces the arguments and approves in one step. §9 calls it the
        standout of ``postgen``'s approval card, and the reason is arithmetic:
        correcting a path costs nothing, while rejecting costs a turn and the
        model often makes the same mistake again.
        """
        authorise(authorization)
        pending = runtime.approvals.get(approval_id)
        if pending is None:
            # Gone means answered, timed out, or the run ended. All three are
            # "too late" rather than an error the client should retry.
            raise HTTPException(status_code=410, detail="that approval is no longer pending")

        decision = str(body.get("decision", "reject")).lower()
        if decision not in ("accept", "reject", "edit"):
            raise HTTPException(status_code=400, detail="decision must be accept, reject or edit")

        if decision == "edit":
            arguments = body.get("arguments")
            if not isinstance(arguments, dict):
                raise HTTPException(status_code=400, detail="edit needs an arguments object")
            pending.arguments = arguments

        pending.approved = decision in ("accept", "edit")
        pending.decided.set()
        return {"id": approval_id, "decision": decision}

    @app.exception_handler(HTTPException)
    async def _http_error(_request: Request, exc: HTTPException) -> JSONResponse:
        return JSONResponse(status_code=exc.status_code, content={"error": exc.detail})

    return app


async def _stream(session: Session, since_id: int, request: Request) -> AsyncIterator[bytes]:
    """Replay, then follow.

    The backlog is drained before subscribing, and the subscription is taken
    *first* so nothing recorded between the two is lost. Doing it the other way
    round leaves a gap exactly the width of the replay — which is longest for the
    clients that most need resumption.
    """
    queue = session.subscribe()
    try:
        for event in session.since(since_id):
            yield event.sse().encode("utf-8")

        seen = session.events[-1].id if session.events else since_id

        if not session.running and queue.empty():
            # Already finished and fully replayed. Close rather than hold the
            # connection open forever: a client watching a finished session is
            # reading history, and an SSE stream that never ends looks to the
            # extension exactly like a run still in progress.
            return

        while True:
            if await request.is_disconnected():
                return
            try:
                event = await asyncio.wait_for(queue.get(), timeout=15.0)
            except TimeoutError:
                # A comment frame. Proxies and load balancers close idle
                # connections, and a run can legitimately think for a minute.
                yield b": keep-alive\n\n"
                if not session.running:
                    return
                continue

            if event.id <= seen and not _is_transient(event):
                continue
            seen = max(seen, event.id)
            yield event.sse().encode("utf-8")

            if event.type is EventType.END:
                return
    finally:
        session.unsubscribe(queue)


def _is_transient(event) -> bool:
    return event.type in (EventType.ASSISTANT_DELTA, EventType.HEARTBEAT)
