package rules

import (
	"go/ast"
	"os"
	"path/filepath"
	"strings"

	"gitlab.cept.gov.in/it-2.0/dakcoder/gotools/internal/workspace"
)

// Legacy rules detect pre-template patterns, as found in the pao-generation
// services. They run only under `legacy_audit`, never under `rules_lint`.
//
// Keeping them separate is deliberate. A pao-era service trips roughly 1,300
// template-compliance findings; surfacing those during an ordinary edit would
// bury the two violations the developer actually introduced. Legacy detection
// is a distinct question — "how far is this service from the template, and in
// what specific ways" — asked deliberately, at the start of a migration.

// legacyGeneration maps an old library to its replacement.
var legacyGeneration = map[string]string{
	"gitlab.cept.gov.in/it-2.0-common/api-server":       "n-api-server",
	"gitlab.cept.gov.in/it-2.0-common/api-db":           "n-api-db",
	"gitlab.cept.gov.in/it-2.0-common/api-log":          "n-api-log",
	"gitlab.cept.gov.in/it-2.0-common/api-bootstrapper": "n-api-bootstrapper",
	"gitlab.cept.gov.in/it-2.0-common/api-validation":   "n-api-validation",
}

// LegacyLibGeneration detects the pre-`n-` common libraries. This is the single
// most reliable signal that a service predates the template, and it is usually
// the last step of a migration rather than the first — the DTO and routing
// changes have to land before the library swap will compile.
var LegacyLibGeneration = Rule{
	ID:       "legacy-lib-generation",
	Severity: SeverityError,
	Legacy:   true,
	Summary:  "service uses the api-* library generation instead of n-api-*",
	Citation: "new-template/go.mod",
	Check: func(p *Pass) {
		for _, f := range p.WS.Files {
			for path, spec := range importSpecs(f) {
				for old, replacement := range legacyGeneration {
					if path == old || strings.HasPrefix(path, old+"/") {
						p.At(f, spec).
							Fix("migrate to gitlab.cept.gov.in/it-2.0-common/%s", replacement).
							Report("legacy library %q; the template uses %s", path, replacement)
					}
				}
			}
		}
	},
}

// LegacyRoutesFile detects a central routes package.
var LegacyRoutesFile = Rule{
	ID:       "legacy-routes-file",
	Severity: SeverityError,
	Legacy:   true,
	Summary:  "a routes/ package exists; routes belong in each handler's Routes()",
	Citation: "SOP.md §Define the Routes; §main.go",
	Check: func(p *Pass) {
		for _, f := range p.WS.FilesIn(workspace.LayerRoutes) {
			p.AtFile(f).
				Fix("move each route group into the owning handler's Routes() method, then delete this file").
				Report("central routes file; the template registers routes per handler")
		}
		// fx.Invoke(routes.Routes) in main.go is the other half of the pattern.
		if main, ok := p.WS.File("main.go"); ok {
			ast.Inspect(main.AST, func(n ast.Node) bool {
				call, ok := n.(*ast.CallExpr)
				if !ok || callName(call) != "fx.Invoke" {
					return true
				}
				for _, a := range call.Args {
					if strings.Contains(typeString(a), "routes.") {
						p.At(main, call).
							Fix("delete fx.Invoke(routes.Routes); handlers self-register through FxHandler").
							Report("main.go invokes the legacy central route registration")
					}
				}
				return true
			})
		}
	},
}

// LegacyGinHandler detects gin in the service layers.
var LegacyGinHandler = Rule{
	ID:       "legacy-gin-handler",
	Severity: SeverityError,
	Legacy:   true,
	Summary:  "gin appears in handler or repo code",
	Citation: "SOP.md §[handler].go (step 5, no gin.Context)",
	Check: func(p *Pass) {
		for _, f := range p.WS.Files {
			switch f.Layer {
			case workspace.LayerHandler, workspace.LayerRepo, workspace.LayerResponse, workspace.LayerDomain:
			default:
				continue
			}
			if path, spec, ok := f.ImportsAny("github.com/gin-gonic/gin"); ok {
				p.At(f, spec).
					Fix("replace *gin.Context with sctx *serverRoute.Context and return typed responses").
					Report("%s imports %q; the template keeps gin out of every service layer", f.Layer, path)
			}
		}
	},
}

// LegacyManualValidation detects the hand-rolled validator service that
// predates govalid.
var LegacyManualValidation = Rule{
	ID:       "legacy-manual-validation",
	Severity: SeverityError,
	Legacy:   true,
	Summary:  "hand-written validator service instead of generated govalid validators",
	Citation: "SOP.md §Validation",
	Check: func(p *Pass) {
		for _, f := range p.WS.Files {
			if path, spec, ok := f.ImportsAny("github.com/go-playground/validator"); ok {
				p.At(f, spec).
					Fix(`declare validate:"..." tags on the request struct and run govalid ./request.go`).
					Report("direct use of %q; validation is generated by govalid", path)
			}
			funcsIn(f, func(fd *ast.FuncDecl) {
				if fd.Name.Name == "NewValidatorService" {
					p.At(f, fd).
						Fix("delete the validator service; the framework validates from generated validators").
						Report("legacy validator service; govalid replaces it")
				}
			})
			// `binding:"..."` is gin's tag; govalid reads `validate:"..."`.
			structsIn(f, func(name string, _ *ast.TypeSpec, st *ast.StructType) {
				for _, fld := range st.Fields.List {
					tag := tagOf(fld)
					if _, hasBinding := tag.Lookup("binding"); !hasBinding {
						continue
					}
					if _, hasValidate := tag.Lookup("validate"); hasValidate {
						continue
					}
					p.At(f, fld).
						Fix(`replace binding:"..." with validate:"..."`).
						Report("%s.%s uses gin's binding tag; govalid reads validate", name, fieldName(fld))
				}
			})
		}
	},
}

// LegacySwaggo detects swaggo-based documentation, which the template replaces
// with framework-generated docs/v3Doc.json.
var LegacySwaggo = Rule{
	ID:       "legacy-swaggo",
	Severity: SeverityWarning,
	Legacy:   true,
	Summary:  "swaggo generates the API docs instead of the framework",
	Citation: "SOP.md §Running the application and Swagger Docs",
	Check: func(p *Pass) {
		for _, f := range p.WS.Files {
			if path, spec, ok := f.ImportsAny("github.com/swaggo/"); ok {
				p.At(f, spec).
					Fix(`set swagger.generation.mode in configs/config.yaml and read /docs/v3Doc.json`).
					Report("swaggo import %q; the framework generates the OpenAPI document", path)
			}
		}
		for _, rel := range []string{"docs/docs.go", "docs/swagger.json", "docs/swagger.yaml"} {
			if _, err := os.Stat(filepath.Join(p.WS.Root, filepath.FromSlash(rel))); err == nil {
				p.AtPath(rel, 1).
					Fix("delete it; the running service serves /docs/v3Doc.json").
					Report("swaggo artefact present")
			}
		}
	},
}

// LegacyResponseHelper detects the pre-envelope success helper.
var LegacyResponseHelper = Rule{
	ID:       "legacy-response-helper",
	Severity: SeverityError,
	Legacy:   true,
	Summary:  "handleSuccess()-style helper instead of port.StatusCodeAndMessage envelopes",
	Citation: "skill.md §Response DTO Pattern",
	Check: func(p *Pass) {
		for _, f := range p.WS.FilesIn(workspace.LayerHandler) {
			funcsIn(f, func(fd *ast.FuncDecl) {
				if fd.Body == nil {
					return
				}
				for _, helper := range []string{"handleSuccess", "handleError", "handleAbort"} {
					if anyCall(fd.Body, helper) {
						p.At(f, fd).
							Fix("return a typed response embedding port.StatusCodeAndMessage").
							Report("%s calls %s(); the template returns typed response structs", fd.Name.Name, helper)
						return
					}
				}
			})
		}
	},
}

// httpParamTypes are the parameter types that make a function an HTTP handler.
var httpParamTypes = []string{
	"gin.Context", "http.ResponseWriter", "http.Request", "serverRoute.Context",
}

// LegacyHandmadeHealth detects a hand-written health endpoint, which the
// framework provides through configuration.
//
// The name alone is not enough to identify one. The first version of this rule
// matched any function whose name contained "healthcheck", and it duly flagged
// `TestHealthCheckHandler_Success` in the legacy corpus's test suite — a
// finding that is not actionable and, being a warning, is exactly the kind of
// noise that teaches people to stop reading warnings.
//
// So the rule now requires what a health *handler* actually has: a non-test
// file, and an HTTP-shaped parameter. `func HealthCheckHandler(c *gin.Context)`
// still matches; a test that exercises it does not.
var LegacyHandmadeHealth = Rule{
	ID:       "legacy-handmade-health",
	Severity: SeverityWarning,
	Legacy:   true,
	Summary:  "hand-written health handler instead of server.healthcheck config",
	Citation: "configs/config.yaml §server.healthcheck",
	Check: func(p *Pass) {
		for _, f := range p.WS.Files {
			if f.Layer == workspace.LayerTest {
				continue
			}
			funcsIn(f, func(fd *ast.FuncDecl) {
				n := fd.Name.Name
				if isTestFunc(n) {
					return
				}
				if !strings.Contains(strings.ToLower(n), "healthcheck") && !hasSuffixFold(n, "healthz") {
					return
				}
				if !hasHTTPParam(fd) {
					return
				}
				p.At(f, fd).
					Fix("enable server.healthcheck.expose and set server.healthcheck.path in configs/").
					Report("hand-written health handler %s; the framework exposes one from config", n)
			})
		}
	},
}

// isTestFunc reports whether a name is a Go testing entry point. Test files are
// already excluded by layer, but a helper named TestHealthCheckSetup in a
// non-test file would slip through on name alone.
func isTestFunc(name string) bool {
	for _, prefix := range []string{"Test", "Benchmark", "Fuzz", "Example"} {
		if strings.HasPrefix(name, prefix) {
			return true
		}
	}
	return false
}

// hasHTTPParam reports whether a function takes an HTTP request context.
func hasHTTPParam(fd *ast.FuncDecl) bool {
	for _, t := range params(fd) {
		for _, want := range httpParamTypes {
			if strings.Contains(t, want) {
				return true
			}
		}
	}
	return false
}

// LegacyGoWork detects a go.work file, which is a local development artefact
// that should not be committed in a single-module service.
var LegacyGoWork = Rule{
	ID:       "legacy-go-work",
	Severity: SeverityWarning,
	Legacy:   true,
	Summary:  "go.work is committed; template services are single-module",
	Citation: "new-template layout",
	Check: func(p *Pass) {
		for _, rel := range []string{"go.work", "go.work.sum"} {
			if _, err := os.Stat(filepath.Join(p.WS.Root, rel)); err == nil {
				p.AtPath(rel, 1).
					Fix("remove it and gitignore it; it is a local workspace artefact").
					Report("%s is committed", rel)
			}
		}
	},
}

// legacyArtifacts are build and test outputs that should never be committed.
var legacyArtifacts = []string{
	"gin.log", "cover.html", "coverage", "test_results.txt", "preprod.yaml.txt",
}

// LegacyCommittedArtifacts detects committed build output.
var LegacyCommittedArtifacts = Rule{
	ID:       "legacy-committed-artifacts",
	Severity: SeverityWarning,
	Legacy:   true,
	Summary:  "build, log or coverage output is committed",
	Citation: "new-template layout",
	Check: func(p *Pass) {
		for _, rel := range legacyArtifacts {
			if _, err := os.Stat(filepath.Join(p.WS.Root, rel)); err == nil {
				p.AtPath(rel, 1).
					Fix("delete it and add it to .gitignore").
					Report("committed build/test artefact %s", rel)
			}
		}
	},
}
